### ISSUE TITLE
App Crashing When Adding User Mid-Game

### ISSUE THREAD

**Issue by nickheidke** [thunderblaster/cards#4]
When a new player joins a game that's in progress, the app can crash. I was able to trace the error when this error occurs:

    /Users/nickh/Source/cards/app/server.js:60
                io.to(socket.id).emit('dealblack', rooms[socket.room].currentBlack);
                                                                      ^

    TypeError: Cannot read property 'currentBlack' of undefined
    at Socket.<anonymous> (/Users/nickh/Source/cards/app/server.js:60:71)
    at Socket.emit (events.js:198:13)
    at /Users/nickh/Source/cards/app/node_modules/socket.io/lib/socket.js:528:12
    at process._tickCallback (internal/process/next_tick.js:61:11)

**Comment by thunderblaster** [comment]
I think the commit in late-joiner-branch fixes, can you confirm?

Explanation of bug: I previously added a feature to check if a user joining a room was a returning user who had previously disconnected during this session and if so, retain and reinstate their score.  This was handled with an `if` statement checking if the room had previously disconnected users and attempted to match them.  There was then an `else` catching users joining a room that never had any disconnected users. But wait! It's noteworthy that this does *not* handle the (probably common) case where a user disconnected and another unique user has joined. They go down the branch to match disconnected users, but never proceed to the `else` to handle novel users.  This explains why `socket.room` is undefined, because it was never set.

**Comment by thunderblaster** [comment]
Further background: this is what you get when you hastily adding a feature because your wife is annoyed that she lost her score because iOS killed Safari when she was browsing Facebook.
