### ISSUE TITLE
raw json in card text

### ISSUE THREAD

**Issue by lankage** [thunderblaster/cards#42]
Got stuck in a state where everyone was getting raw json rather than html or text in the card text view.  This cleared on ending the current round.  Maybe just do a extra html_safe or whatever the view.js equivalent of that is.  

<img width="1342" alt="Screen Shot 2020-04-25 at 8 33 53 PM" src="https://user-images.githubusercontent.com/9486359/80397184-61b79e80-887b-11ea-96a5-0250e2a5cb83.png">

**Comment by thunderblaster** [comment]
The `whitecards` array should always have the full card object, but the view should only be showing the `card_text` property of it.  This was for all users? If so, it shouldn't have anything to do with the client or Vue because they're all independent.  That sounds like the server sent an object like

```
{
     card_id: 401,
     card_text: "{
                       card_id: 401,
                       card_text: "Asians who aren't good at math",
                       selected: true
                 },
    selected: true
}
```

That is, somehow the entire object got set as the `card_text`.  @nickheidke can we check a log for that? @lankage you got an approximate time of this occurring?

**Comment by thunderblaster** [comment]
Here's the relevant view code (index.html, lines 111-118 for me, but I might be on another commit):
```
<ul v-if="selectedcards.length&&!turn">
    <!-- If it is not turn, but players are done submitting cards. This displays all the submitted cards along with who submitted them,... -->
    <li v-for="(card, index) in selectedcards" class="card whitecard" :class="{ selected: card.selected }" :key="card.name">
    <!-- but you cannot choose a winner (because it's not your turn!) -->
        <p v-html="card.card_text"></p>
        <p class="whitecardname">{{card.name}}</p>
     </li>
</ul>
```
Note that clearly the `card` object has a `name` property because it's correctly displaying the name in red in the screenshot.  This reinforces my hunch.  The server must have somehow stuck the object inside the `card_text` property, apparently *before* it had the `name` attached since that appears to be omitted on the inner JSON.  Here's the relevant server code:
```
let selectedcards = []; // Here's a handy (but somewhat redundant) array to hold all the cards selected for play with this black card
for (let i = 0; i < rooms[socket.room].userlist.length; i++) { // Loop through all users in room
    if (rooms[socket.room].userlist[i].selected) { // If they've selected a card (remember, one is the czar and will not have)
        selectedcards.push({ name: rooms[socket.room].userlist[i].name, card_text: rooms[socket.room].userlist[i].selected.card_text, selected: false, card_id : rooms[socket.room].userlist[i].selected.card_text}); // Push to array
    }
}
util.shuffle(selectedcards); // This is important, otherwise the white cards will be displayed in the order of the players in the userlist array which means they wouldn't be anonymous
io.to(socket.room).emit('selectedcards', selectedcards); // Announce the list of selected white cards to the room
```

Note `rooms.userlist.selected` comes from the client, so it's possible some client-side JS is doing something wonky, but that seems unlikely that it'd affect each client and not just one.  It seems like it's corrupted in or before the `userlist` though.  It's gotta be before it's added to `selectedcards` because that includes `name` which our glitched version excludes.  Hmm.  I can try to dig more.
